# Generated by Django 4.2.16 on 2026-09-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_contenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Nom du site')),
                ('site_description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('site_tagline', models.CharField(blank=True, max_length=255, verbose_name='Slogan')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon (carré, ex: 512x512)')),
                ('image_partage', models.ImageField(blank=True, help_text='Utilisée quand un lien du site est partagé sans image propre. Idéal: 1200x630px.', null=True, upload_to='site/', verbose_name='Image de partage par défaut')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
