# Generated by Django 4.2.16 on 2026-09-08 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/galerie/%Y/%m/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=255, verbose_name='Legende')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': "Image d'article",
                'verbose_name_plural': "Images d'article",
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
